services:
  symfony:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: 'task_user'
      POSTGRES_PASSWORD: 'task_pwd'
      POSTGRES_DB: 'task_db'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - symfony_network

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - symfony_network
    depends_on:
      - symfony

volumes:
  pgdata:

networks:
  symfony_network:
    driver: bridge